### ISSUE TITLE
Update the tag for the last commit.

### ISSUE THREAD

**Issue by aavrug** [Talesoft/tale-pug#1]
Hey Torben,

Please update the tag for the last commit so when we will use tale-pug we will get the tale-pug file, not the tale-jade file. Just because the tag is not added and didn't update the packagist still getting the tale-jade file.

**Comment by TorbenKoehn** [comment]
I will! Sorry :)

**Comment by TorbenKoehn** [comment]
Check out `^1.5.1` :)

**Comment by aavrug** [comment]
Thanks. :)

**Comment by jacmoe** [comment]
Aha! So this is the successor to Tale-jade ?
I found you! :p

I will update my project if this is the case 😄

**Comment by TorbenKoehn** [comment]
Hey @jacmoe, this is the successor to Tale Jade, but it wasn't changed in functionality, only renamed and the `.pug`-extension was added.

@kylekatarnls and me are writing Phug currently, I've seen you're already migrating :)

If you're migrating, stay with Phug. It will be the new, big engine ;)
